### ISSUE TITLE
Wrong address from XPUB

### ISSUE THREAD

**Issue by mariodian** [Bit-Wasp/multisig#1]
I've included your bitcoin libraries into my codeigniter 3 project and when I try to generate wallet addresses from the Electrum's XPUB, it gives me the right results most of the time, but sometimes it doesn't.

For example with the XPUB provided in the code, results for "m/0/2" and "m/0/14" are wrong, everything else is OK. 

In case of "m/0/2" your code gives me 1B3RQ4QKocRE7MFVDpMMmgyswF2DeMEfS6 and Electrum gives me 16wjYM9D46xPYHHUQp7XwotgLwT56ZPZux

In case of "m/0/14" I'm getting 1JEKgyHAb4tx5EkPpMhWzACxTVGsW2Z7Xo but Electrum gives me 14tk9sYRDXXbya6Q2ZJLs1hHZ2mcpRbybS

```
<?php
$xpub = 'xpub661MyMwAqRbcGtMQDiA8n7E15sH2cA6qdE1kdiQuMjdnNoCwbFMuenQh29mrER4txDBDsuJUPAUZSd9J4qpxFtNBFEzep2cJVDku9UVVAfY';

$address = BIP32::build_address($xpub, "0/2");

echo $address[0]; // Outputs 1B3RQ4QKocRE7MFVDpMMmgyswF2DeMEfS6
```

I tried different PHP servers (OSX, ubuntu) because I thought it's perhaps an issue with php5-gmp library but it gives me the same wrong results. 

I also tried using BitcoinLib and BIP32 to generate addresses for multisig wallets (of course with different XPUBs) and there are much more wrong results (~4 out of every 20 addresses). 

BTW results with XPUB from my TREZOR wallet were OK. I also checked with http://bip32.org and it shows me same addresses as Electrum does, so it seems there are some issues with your code.

**Comment by afk11** [comment]
Hey, thanks for posting! 

This is actually an old project, I can't attest to it's reliability for anything right now. Most of the code it uses can be found in this library: https://github.com/Bit-Wasp/bitcoin-lib-php available through composer. 

Testing the code you posted above against this library produces the correct address! 

I wouldn't advise relying on the code in this bit-wasp/multisig repository as it's not maintained, and didn't see much use back in the day. The bitcoin-lib-php library has been maintained since then, and has some of the soft-fork requirements that have come about since I wrote this!

With all that said, using Bit-Wasp/bitcoin-php might be best. It's far more complete/tested, and probably easier to develop applications around.

**Comment by mariodian** [comment]
I switched to bitcoin-lib php since, but a multisig wallet code gives me wrong results as well. "m/0/i" seems ok for 3 tested XPUBs so far though.

I will try bitcoin-php for multisig to check if it's ok. Performance wise it seems the same. Thank you for the reply.

**Comment by mariodian** [comment]
OK, so I switched to Bit-Wasp/bitcoin-php and after brief testing I think it works correctly with numerous XPUBs being tested. I also get correct addresses for my multisig wallet.

Btw the only reason I wanted to use Bit-Wasp/multisig is because it takes only 30ms to generate an address. It takes about 4x more to do the same with Bit-Wasp/bitcoin-php but I guess that extra time is because it's much more reliable.

Anyway thank you again. 

I'm closing the issue as you're no longer maintaining this code.

**Comment by afk11** [comment]
Indeed it was for a reason - Point multiplication now run at constant time, instead of leaking information about the private key.

Good luck!
